version: "{build}"
branches:
  only:
  - master
  - appveyor
  - hunter
configuration:
  - Release
environment:
  matrix:
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
      GENERATOR: "Visual Studio 15 2017 Win64"

    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
      GENERATOR: "Visual Studio 15 2017"

    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
      GENERATOR: "Visual Studio 14 2015 Win64"
cache:
  - C:\.hunter\_Base\Cache -> cmake\HunterConfig.cmake

before_build: |
  if not exist build mkdir build
  cd build
  cmake -G "%GENERATOR%" .. -DEVMC_TESTING=ON -DEVMC_EXAMPLES=ON

build:
  project: c:/projects/evmc/build/evmc.sln
  parallel: true
  verbosity: minimal

after_build: |
  C:\projects\evmc\build\test\Release\evmc-test.exe
